config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"
  resources :boards do
    resources :lists
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :boards, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :set_board, only: [:edit, :update, :show, :destroy]


def index
    @boards = current_user.boards
  end

  def new
    @board = Board.new
  end

  def create  
    @board = current_user.boards.new(board_params)
      if @board.save
      redirect_to boards_path 
      else
      render :new
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if @board.update(board_params) 
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

private

def set_board
  @board = current_user.boards.find(params[:id])
end

def board_params
  params.require(:board).permit(:name)
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = @board.lists
  end
  
  def show
  end

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)
      if @list.save
        redirect_to board_lists_path
      else
        render :new
      end
    end 
  
    def edit
    end
  
    def update
    if @list.update(list_params)
      redirect_to board_list_path(@board, @list)
    else
      render :edit
    end
    end

  def destroy
    @list.destroy
    redirect_to board_list_path(@board)
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end
  
  def set_list
    @list = List.find(params[:board_id])
  end
  def list_params
    params.require(:list).permit(:name, :priority, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/boards/edit.html.erb
<%= render "form" %>

app/views/boards/index.html.erb
<h1> Boards </h1>

<% @boards.each do |bods| %>

<div>
<h3><%= link_to bods.name, board_path(bods) %>

<% end %>

app/views/boards/new.html.erb
<%= render "form" %>

app/views/boards/show.html.erb
<h2><%= @board.name %> <h2> 
<br/>

<h3><%= link_to "edit", edit_board_path(@board) %></h3>

<h3><%= link_to "delete board", board_path(@board), method: :delete %></h3>

<h3><%= link_to "lists", new_board_list_path%></h3>

app/views/layouts/_navbar.html.erb
  <nav class= "ui menu"> 
  <%= link_to 'Boards', boards_path, class: "item" %>
  <%= link_to 'Add Board', new_board_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: "item" %>
      <%= link_to 'Register', new_user_registration_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

  <%= render "layouts/navbar" %>
      <div class = "ui container" >
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: @list, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>

    <%= f.label :priority %>
    <%= f.text_field :priority, class: "input" %>
  </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form" %>

app/views/lists/index.html.erb
<h1> Lists </h1>

<% @lits.each do |li| %>

<div>
<h3><%= link_to li.name, board_lists_path(board:[id]) %>

<% end %>

app/views/lists/new.html.erb
<%= render "form" %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>